### PR TITLE
Filter qbt list command by torrent state.

### LINKED ISSUE #46: Move not working on qBit 4.5.2
First of all thank you for this tool! 

While trying to use the 'move' option I get a successful message but categories remain unchanged. I don't see any pertinent info in qbit logs other than a successful web login. 

However when manually changing a torrents category in web-ui there is related info in the log. Let me know if I can provide more info.

**Edit:** Looks to may be a 4.5.x issue - move works as intended on 4.3.9

```
qbittorrent version: qbittorrent-nox v4.5.2 on debian
qbt-cli version: tried dev / 1.0.0 / 0.16.0
```
```
qbt move --from t1 --to t2

Found 1 matching torrents to move from (t1) to (t2)
Successfully moved 1 torrents from (t1) to (t2)
```

### PR DESCRIPTION
**Pull request by xel86**
Allows for the `qbt list` command to be filtered to list only the torrents specified by a state argument, like `downloading`.

For example:
`qbt list --filter=active` will list all active torrents currently downloading or uploading.
`qbt list` will continue to list all torrents.

New flags:

* `--filter,-f - takes a single qbit state as filter`
* `--category,-c - takes a single category`
* `--tag,-t - takes a single tag`
* `--hashes,-h - takes one or multiple hashes separated by | pipe: "hash1|hash2"`

Also removed the `uploading` TorrentFilter from `domains.go` since it is not a valid filter for the qbittorrent api, and added the missing `errored` filter.  (https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-list)

Fixes #46

### CODE REVIEW

File: cmd/list.go [hunk 1]
```diff
@@ -3,24 +3,28 @@ package cmd
...
+		Use:   "list [state]",
 		Short: "List torrents",
-		Long:  `List all torrents`,
+		Long: `List all torrents, or torrents with a specific state. Available states:
+all, downloading, seeding, completed, paused, active, inactive, resumed, 
+stalled, stalled_uploading, stalled_downloading, errored`,
+		Example: `qbt list downloading`,
 	}
-	command.Flags().BoolVar(&json, "json", false, "print to json")
+	command.Flags().BoolVar(&json, "json", false, "Print to json")
```
Comment (ludviglundgren) [inline cmd/list.go:27]: While this works, I would add a new Flag like `filter`,`state` or `status` that takes the argument. It would then become `qbt list --filter=downloading` for example.

And then we can simplify the check for args below.

I would add a new `StringVar` Flag [like here](https://github.com/ludviglundgren/qbittorrent-cli/blob/develop/cmd/add.go#L48).

```golang
command.Flags().StringVar(&state, "state", "", "Filter by state: all, downloading, seeding, completed, paused, active, inactive, resumed, 
stalled, stalled_uploading, stalled_downloading, errored")
```

File: cmd/list.go [hunk 2]
```diff
@@ -45,14 +49,44 @@ func RunList() *cobra.Command {
...
+
+			if err != nil {
+				fmt.Fprintf(os.Stderr, "ERROR: could not get torrents %v\n", err)
+				os.Exit(1)
+			}
+
+			if len(torrents) < 1 {
+				fmt.Printf("No torrents found with state \"%s\"\n", state)
+				return
+			}
```
Comment (ludviglundgren) [inline cmd/list.go:88]: With that new flag this could then be simplified a bit, and I would inverse the logic. So `if state != ""` then do the filtering, else just do `GetTorrents()`.

You can also make it simpler and do the err check outside of the if else, and check torrent len there as well. And making it `if len(torrents) == 0 {` would improve the readability a bit imo.

File: pkg/qbittorrent/domain.go [hunk 3]
```diff
@@ -162,9 +163,6 @@ const (
 	// Torrent is stalled
 	TorrentFilterStalled TorrentFilter = "stalled"
 
-	// Torrent is being seeded and data is being transferred
-	TorrentFilterUploading TorrentFilter = "uploading"
-
```
Comment (ludviglundgren) [inline pkg/qbittorrent/domain.go:167]: Are you certain this was actually removed?

**Review by ludviglundgren — COMMENTED** [review]
Hello! Thanks for the PR :)

Left some feedback on good and simple improvements!

**Review by ludviglundgren — APPROVED** [review]
I did _just a bit_ of refactoring :smile: 

Changed the args from state to filter and also added `category, tag, hashes`.

Updated the qbit client to take a context everywhere, so requests can be cancelled.

More to come!

**Comment by xel86** [comment]
Sorry about that, been very busy lately and completely forgot about this PR. Thanks for the improvements :)
